# Generated by Django 5.1.1 on 2025-07-09 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_follow_following_alter_follow_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                condition=models.Q(("user", models.F("following")), _negated=True),
                name="prevent_self_follow",
            ),
        ),
    ]
